import typescript from '@rollup/plugin-typescript';
import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import copy from 'rollup-plugin-copy';

const isProd = (process.env.BUILD === 'production');
const vaultPath = process.env.VAULT_PATH;

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

const plugins = [
  typescript(),
  nodeResolve({browser: true}),
  commonjs(),
];

// Only add the copy plugin if a VAULT_PATH is provided in .env
if (vaultPath) {
  plugins.push(
    copy({
      targets: [
        { src: 'manifest.json', dest: vaultPath },
        { src: 'styles.css', dest: vaultPath },
        { src: 'main.js', dest: vaultPath },
      ],
      hook: 'writeBundle'
    })
  );
}

export default {
  input: 'main.ts',
  output: {
    dir: '.',
    sourcemap: 'inline',
    sourcemapExcludeSources: isProd,
    format: 'cjs',
    exports: 'named',
    banner,
  },
  external: ['obsidian'],
  plugins: plugins
};